const ERROR_CODE_WRONG_DATA = 400;
const ERROR_CODE_DATA_NOT_FOUND = 404;
const ERROR_CODE_DEFAULT = 500;
const VALIDATION_ERROR = 'ValidationError';
const VALIDATION_ID_ERROR = 'CastError';

module.exports = {
  ERROR_CODE_DATA_NOT_FOUND,
  ERROR_CODE_WRONG_DATA,
  ERROR_CODE_DEFAULT,
  VALIDATION_ERROR,
  VALIDATION_ID_ERROR,
};
